import tweepy
import configparser


# read configs

config= configparser.ConfigParser()
config.read("config.ini")

api_key= config["twitter"]["api_key"]
api_key_secret=config["twitter"]["api_key_secret"]
access_token=config["twitter"]["access_token"]
access_token_secret= config["twitter"]["access_token_secret"]

# Authentication

auth= tweepy.OAuthHandler(api_key,api_key_secret)
auth.set_access_token(access_token,access_token_secret)
api= tweepy.API(auth)
public_tweets=api.home_timeline()
# print(public_tweets)
for tweet in public_tweets:
    print(tweet.txt)


#Output:
C:/Users/bcm/AppData/Local/Programs/Python/Python310/python.exe e:/User/Twitter_sentiment/Twitter_api.py
Traceback (most recent call last):
  File "e:\User\Twitter_sentiment\Twitter_api.py", line 20, in <module>
    public_tweets=api.home_timeline()
  File "C:\Users\bcm\AppData\Local\Programs\Python\Python310\lib\site-packages\tweepy\api.py", line 33, in wrapper
    return method(*args, **kwargs)
  File "C:\Users\bcm\AppData\Local\Programs\Python\Python310\lib\site-packages\tweepy\api.py", line 46, in wrapper
    return method(*args, **kwargs)
  File "C:\Users\bcm\AppData\Local\Programs\Python\Python310\lib\site-packages\tweepy\api.py", line 331, in home_timeline
    return self.request(
  File "C:\Users\bcm\AppData\Local\Programs\Python\Python310\lib\site-packages\tweepy\api.py", line 267, in request
    raise BadRequest(resp)
tweepy.errors.BadRequest: 400 Bad Request
215 - Bad Authentication data.
